# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SunflowerProject' do
pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
pod 'Firebase/Firestore'


  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SunflowerProject


    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

    pod 'RNSVG', :path => '../node_modules/react-native-svg'

  end

